### ISSUE TITLE
Installation path of the packages under different R versions

### ISSUE THREAD

**Issue by kguidonimartins** [iroddis/asdf-R#13]
Hi @n8sty, thanks for continuing this work. I was waiting for the update of this plugin.

I haven't used asdf for R yet, so I still have no idea how different R versions handle the installation path of the packages. Could you tell me if it is in the R_CONFIGURE_OPTIONS variable that I inform the installation path of the packages?

My current installed version (4.0.3) uses the R_LIBS_USER variable to indicate a path other than the default for installing packages. How does asdf handle this?

**Comment by n8sty** [comment]
The new R plugin for asdf is actually here: https://github.com/taiar/asdf-R, per the https://github.com/asdf-vm/asdf-plugins#plugin-list.

I would say, try it out and see, but that off the top of my head `R_CONFIGURE_OPTIONS` is used for installing R rather than packages - I think your `R_LIBS_USER` should be safe.

**Comment by kguidonimartins** [comment]
Thanks for the links. I didn't see this note in the README: https://github.com/taiar/asdf-R#building-r-shared-library

It seems like the information I was looking for. I'll try it.

Thanks for your time.
